### ISSUE TITLE
Shouldn't it only nest if there is more than one selector ?

### ISSUE THREAD

**Issue by jpillora** [thomaspierson/libcss2less#12]
``` css
body .navbar .nav > li > a {
  color: #333;
  font-weight: bold;
}
```

compiles to

``` css
body {
    .navbar {
        .nav {
            > {
                li {
                    > {
                        a {
                            color: #333;
                            font-weight: bold;
                        }
                    }
                }
            }
        }
    }
}

```

**Comment by vin-ai** [comment]
It happening with me also:

when I tried:

``` css
.thumbnail-boxy > .boxy-handle + .caption {
    padding-top: 9px;
}
```

then it produces:

``` css
.thumbnail-boxy {
    & > .boxy-handle {
        + {
            .caption {
                padding-top: 9px;
            }
        }
    }
}
```
