### ISSUE TITLE
Repeats same property when found duplicate selector

### ISSUE THREAD

**Issue by vin-ai** [thomaspierson/libcss2less#16]
I tried:

``` css
#container-fluid,
#row-fluid,
#row-fluid > .span2,
#sidebar-nav,
#wrapper {
    height: 100%;
    min-height: 100%;
}

#container-fluid,
#row-fluid,
#row-fluid > .span2,
#sidebar-nav,
#wrapper {
    height: 100%;
    min-height: 100%;
}

#container-fluid,
#row-fluid,
#row-fluid > .span2,
#sidebar-nav,
#wrapper {
    height: 100%;
    min-height: 100%;
}
```

and it produces:
here height and min-height is repeating thrice, because above same selector repeating thrice

``` css
#container-fluid,#row-fluid,#row-fluid &>.span2,#sidebar-nav,#wrapper {
    height: 100%;
    min-height: 100%;
    height: 100%;
    min-height: 100%;
    height: 100%;
    min-height: 100%;
}
```

**Comment by rjmunro** [comment]
Or, more simply:

``` css
#hello {
    color: blue;
}
#hello {
    color: blue;
}
```

produces:

``` css
#hello {
    color: blue;
    color: blue;
}
```

I don't think this is a bug. The root cause of the problem is that your original CSS is bad.
