### ISSUE TITLE
Invalid conversion: "p + h4"

### ISSUE THREAD

**Issue by askaliuk** [thomaspierson/libcss2less#17]
Found invalid conversion case. Please check example below:

CSS:

``` css
.marketing {
margin: 60px 0;
}
.marketing p + h4 {
margin-top: 28px;
} 
```

LESS:

``` css
.marketing {
    margin: 60px 0;
    p {
        + {
            h4 {
                margin-top: 28px;
            }
        }
    }
}
```

**Comment by chenasraf** [comment]
Yeah, also happened to me

**Comment by rjmunro** [comment]
This looks like a very similar issue to #4. Probably a slight modification to the fix for that is all that is required.

**Comment by tanob** [comment]
Got into the same issue, below are the two cases I had problems in the conversion.

 # 1

input:

``` css
header.main li + li {
    border-left: 1px solid #cfcfcf;
}
```

output that produces syntax error:

``` css
header.main {
    li {
        + {
            li {
                border-left: 1px solid #cfcfcf;
            }
        }
    }
}
```

correct output:

``` css
header.main {
    li + li {
                border-left: 1px solid #cfcfcf;
    }
}
```

 # 2

input:

``` css
.icon-container + div {
    padding-top: 5px;
}
```

output that produces syntax error:

``` css
.icon-container {
    + {
        div {
            padding-top: 5px;
        }
    }
}
```

correct output:

``` css
 .icon-container {
    & + div {
        padding-top: 5px;
    }
 }
```

Thanks
