### ISSUE TITLE
CSS Media querys doesnt work

### ISSUE THREAD

**Issue by sprengel** [thomaspierson/libcss2less#21]
when i import css with this, it generates unvalid stuff and less shows an error
@media (max-width: 990px) {
    body {
        background-position: -468px 0;
    }
}

**Comment by MGDSoft** [comment]
:+1: N1 tools thx

**Comment by lingo** [comment]
More info:

This:

``` css
@media screen and (max-width: 1000px) {
    #hello {
        color: blue;
    }

    #hello #buddy {
        background: red;
    }
}
```

Generated this, which made me queasy :)

``` css
@media {
    screen {
        and {
            (max-width: {
                1000px) {
                    #hello;
                }
            }
        }
    }
}
color: {
    #FFF; {
        #hello #buddy;
    }
}
```
